#!/bin/bash

# Check if 'p_num' parameter is provided
if [ "$#" -eq 1 ]; then
    python3 "/Users/kiharari/Documents/Bilibili spider application develping/From-API-to-Bilibili/workflow/main.py" "$1"
elif [ "$#" -eq 2 ] && [ "$2" = "p_num" ]; then
    python3 "/Users/kiharari/Documents/Bilibili spider application develping/From-API-to-Bilibili/workflow/main.py" "$1" p_num
else
    echo "Usage: bilidl bvid [p_num]"
    exit 1
fi
